services:
  assign-manager-api:
    # 使用當前目錄的Dockerfile構建映像
    build: 
      context: .
      args:
        - REPO_URL=${REPO_URL:-https://github.com/abonscjlin/assign_manager.git}
    
    # 容器名稱
    container_name: assign-manager-api
    
    # 端口映射：本機7777端口 -> 容器7777端口
    ports:
      - "7777:7777"
    
    # 目錄掛載：將專用的docker目錄掛載到容器對應位置
    volumes:
      - ~/docker/assign_manager/result:/app/result
      - ~/docker/assign_manager/employee_list.csv:/app/employee_list.csv:ro
      - ~/docker/assign_manager/result.csv:/app/result.csv:ro
      # 掛載代碼存儲volume，以便在容器重啟時保持代碼狀態
      - assign_manager_code:/app/.git
    
    # 環境變數
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
      - REPO_URL=${REPO_URL:-https://github.com/abonscjlin/assign_manager.git}
      - GIT_BRANCH=${GIT_BRANCH:-main}
    
    # 重啟策略
    restart: unless-stopped
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 日誌配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 定義volumes用於數據持久化
volumes:
  assign_manager_data:
    driver: local
  assign_manager_code:
    driver: local 